### ISSUE TITLE
Error on start up: void function typecase

### ISSUE THREAD

**Issue by bassu** [emacsfodder/emacs-mainline#3]
Latest Emacs 24.3

Here's the debugging output:

Debugger entered--Lisp error: (void-function typecase)
  (typecase func (symbol (fset func (memoize-wrap (symbol-function func))) func) (function (memoize-wrap func)))
  memoize(roundstub-left-xpm)
  eval-buffer(#<buffer  *load*-184344> nil "foo/.emacs.d/main-line.el" nil t)  ; Reading at buffer position 24098
  load-with-code-conversion("foo/.emacs.d/main-line.el" "foo/.emacs.d/main-line.el" nil t)
  require(main-line)
  eval-buffer(#<buffer  *load*> nil "foo/.emacs" nil t)  ; Reading at buffer position 234
  load-with-code-conversion("foo/.emacs" "foo/.emacs" t t)
  load("~/.emacs" t t)
  #[0 "^H\205\262^@ \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\202;^@\313\307\314\315#\203*^@\316\202;^@\313\307\314\317#\203:^@\320\nB^R\321\202;^@\316\322^S\323^A\322\211#\210^K\322=\203a^@\324\325\326\307^H\32$
  command-line()
  normal-top-level()

**Comment by amonsch** [comment]
This was fixed, see here:
https://github.com/emacsfodder/emacs-mainline/commit/3eb920d19742f4996275c7a720382ccbcc0a87d4
